---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cosmonaut-reportes"
spec:
  selector:
    matchLabels:
      app: "cosmonaut-reportes"
  template:
    metadata:
      labels:
        app: "cosmonaut-reportes"
    spec:
      serviceAccountName: cosmonaut-services
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: "cosmonaut-reportes"
          image: "gcr.io/cosmonaut-uat/cosmonaut/reportes:$TAG"
          env:
            - name: MICRONAUT_APPLICATION_JSON
              value: '{"datasources":{"default":{"password":"c05MoN4uTD3"}},"kubernetes":{ "client":{ "config-maps":{"enabled":true,"labels":[{"environment":"dev"}]} }}}'
            - name: APLICACION_PUERTO
              value: "8080" 
          ports:
            - name: web
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "cosmonaut-reportes"
spec:
  selector:
    app: "cosmonaut-reportes"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 8080
